{"name":"输入正确的用户名、错误的密码","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [密码错误111] but found []","trace":"java.lang.AssertionError: expected [密码错误111] but found []\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:496)\r\n\tat org.testng.Assert.assertEquals(Assert.java:125)\r\n\tat org.testng.Assert.assertEquals(Assert.java:178)\r\n\tat org.testng.Assert.assertEquals(Assert.java:188)\r\n\tat com.ly.javaselenium.webdriver.testSuites.LoginTest.user1pass0(LoginTest.java:60)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:639)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:774)\r\n\tat org.testng.TestRunner.run(TestRunner.java:624)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:359)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:261)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1116)\r\n\tat org.testng.TestNG.run(TestNG.java:1024)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"输入正确的用户名、错误的密码","steps":[{"name":"输入用户名、错误的密码","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1635306392253,"stop":1635306392254}],"attachments":[{"name":"失败截图","source":"cf4c20d2-b1b5-4b90-b7b2-7e08235caeab-attachment"}],"parameters":[],"start":1635306392250,"stop":1635306393414,"uuid":"e20dad82-5e9f-4e0c-b944-81d2caaa3554","historyId":"2ef2e0f154e3bf0f07fefee4e21f32bf","fullName":"com.ly.javaselenium.webdriver.testSuites.LoginTest.user1pass0","labels":[{"name":"package","value":"com.ly.javaselenium.webdriver.testSuites.LoginTest"},{"name":"testClass","value":"com.ly.javaselenium.webdriver.testSuites.LoginTest"},{"name":"testMethod","value":"user1pass0"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"D:/Java-work/JavaSelenium"},{"name":"subSuite","value":"com.ly.javaselenium.webdriver.testSuites.LoginTest"},{"name":"host","value":"liyanb-1"},{"name":"thread","value":"1060@liyanb-1.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"输入操作"},{"name":"feature","value":"登录测试"}],"links":[]}